image: node

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - bash test.sh

deploy:
  stage: deploy
  environment:
    name: production
    url: example.com
  script:
    - bash deploy.sh
  artifacts:
    paths:
      - build/

  only:
    - main