version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    ports:
      - '8080:80'
      - '443:443'
      - '22:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./frontend/:/config/workspace/
    ports:
      - 8443:8443
    restart: unless-stopped
  frontend:
      logging:
        options:
          mode: non-blocking
          max-size: 4m
      container_name: frontend
      image: frontend
      restart: always
      build:
        context: .
        dockerfile: ./frontend/Dockerfile
      volumes:
        - ./frontend/:/app/
      ports:
        - "3000:3000"
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    volumes:
      - ./jobs/config.toml:/etc/gitlab-runner/config.toml
      - ./jobs/gitlab.yml:/home/git/gitlab/config/gitlab.yml
      - build-artifact:/artifact
      - /var/run/docker.sock:/var/run/docker.sock 
  production:
    container_name: production
    build:
      context: .
      dockerfile: ./production/Dockerfile
    ports:
      - '80:80'
    volumes:
      - build-artifact:/build
volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  build-artifact: