concurrent = 4
check_interval = 0
log_level = "warning"

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Seguridad Runner"
  url = "http://gitlab"
  id = 2
  token = "mMumLTzVV83HuZzFyXHk"
  token_obtained_at = 2022-11-17T15:17:12Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ruby:2.7"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "desc"
  url = "http://gitlab"
  id = 1
  token = "S3ida8QuWS9KgSZsmLS1"
  token_obtained_at = 2022-11-18T02:26:41Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  builds_dir = "/artifact"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ruby:2.7"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "cicdpipeline_default"
    shm_size = 0

[[runners]]
  name = "desc"
  url = "http://gitlab"
  id = 1
  token = "GLXS_pPjyocQeYU-zs58"
  token_obtained_at = 2022-11-20T04:56:56Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ruby:2.7"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "cicdpipeline_default"
    shm_size = 0
