concurrent = 4
check_interval = 0
log_level = "warning"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner para corred CI/CD seguridad"
  url = "http://gitlab"
  id = 1
  token = "8zdsxTm5Sfh_TRarpzB-"
  token_obtained_at = 2022-11-26T21:06:59Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  builds_dir = "/artifact"
  [runners.custom_build_dir]
    enabled = true
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ruby:2.7"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "cicdpipeline_default"
    shm_size = 0
